### ISSUE TITLE
前来膜拜

### ISSUE THREAD

**Issue by nihaojob** [asang28/vue3-fabric-editor#2]
大佬好，不知道大佬是否感兴趣，我建了一个vue-fabric-editor项目的微信交流群，[QJune](https://github.com/QJune)也在群里，并且多次为项目提交PR，想邀请大佬一起维护，微信13146890191。

**Comment by asang28** [comment]
> 大佬好，不知道大佬是否感兴趣，我建了一个vue-fabric-editor项目的微信交流群，[QJune](https://github.com/QJune)也在群里，并且多次为项目提交PR，想邀请大佬一起维护，微信13146890191。

可以啊，一起学习。
